server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location = / {
        return 302 /gc-visualizer/;
    }

    location /gc-visualizer/ {
        try_files $uri $uri/ /gc-visualizer/index.html;
    }
}
